name: Bug report
description: Report bugs with the mod here
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: "Describe your bug here (Please include any screenshots or videos)."
    validations:
      required: true

  - type: textarea
    id: terminal
    attributes:
      label: "Command Prompt/Terminal logs (if existing)"
      render: bash
    validations:
      required: false

  - type: dropdown
    id: btarget
    attributes:
      label: "What is your build target?"
      options:
        - "Windows"
        - "Mac"
        - "Linux"
        - "Android"
        - "Other (Please include in your summary)"
    validations:
      required: true

  - type: input
    id: buildsummary
    attributes:
      label: "Did you edit anything in this build? If so, mention or summarize your changes."
      placeholder: "Yes, I edited ClientPrefs.hx and tried to add a new setting"
    validations:
      required: true

  - type: checkboxes
    id: buildchecklist
    attributes:
      label: "Issue Checklist."
      description: "Please complete the checklist before submitting your issue."
      options:
        - label: I have checked the issues page to see if my issue has already been reported.
        - label: I have properly titled my issue.
        - label: I am confident I am playing a Vanilla copy of the Mod with Zero Modifcations.
    validations:
      required: true
