name: Feature Request
description: Please request something technical for the mod like a new useful setting or how to improve a mechanic.
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: What feature do you want to get added to the mod?
    validations:
      required: true
  - type: dropdown
    id: eyetest
    attributes:
      label: To test your sight, and reliability, please select the option of what should NOT be requested.
      options:
        - Proper credit that was forgotten
        - Thing that would not cause problems
        - Useful feature
        - A full week or song based on a character or game.
        - Code optimization that would make the game better or faster. (You should make a PR if this is your request, by the way.)
    validations:
      required: true

  - type: checkboxes
    id: featurechecklist
    attributes:
      label: "Feature Checklist."
      placeholder: "Please complete the checklist before submitting your request."
    options:
      - label: I have checked the issues page to see if my request has already been made.
      - label: I have properly titled and explained my request.
    validations:
      required: true
